// This Source Code Form is subject to the terms of the Lyra Public License,
// v1.0. If a copy of the Lyra Public License was not distributed with this file,
// You can obtain one here:
// www.meshiplaw.com/lyra.

use std::net::SocketAddr;
use std::sync::{
    Arc,
    Mutex as StdMutex,
};
use std::time::Duration;

use harmony_core::{
    LuaAsyncExt,
    LuaUserDataAsyncExt,
    Module,
};
use harmony_luau::{
    DescribeInterface,
    DescribeUserData,
    LuauType,
    LuauTypeInfo,
    render_definition_file_with_support,
};
use mlua::{
    FromLua,
    IntoLua,
    Lua,
    LuaSerdeExt,
    Value,
};
use serde::{
    Deserialize,
    Serialize,
};
use tokio::io::{
    AsyncReadExt,
    AsyncWriteExt,
};
use tokio::net::{
    TcpListener as TokioTcpListener,
    TcpStream as TokioTcpStream,
    UdpSocket as TokioUdpSocket,
};
use tokio::sync::Mutex as TokioMutex;
use tokio::sync::RwLock as TokioRwLock;

/// Wrapper for returning raw bytes as a Lua string from methods that lack
/// direct `Lua` access (i.e. those generated by `#[harmony_macros::implementation]`).
struct LuaBytes(Vec<u8>);

impl IntoLua for LuaBytes {
    fn into_lua(self, lua: &Lua) -> mlua::Result<Value> {
        Ok(Value::String(lua.create_string(&self.0)?))
    }
}

impl LuauTypeInfo for LuaBytes {
    fn luau_type() -> LuauType {
        String::luau_type()
    }
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[harmony_macros::interface]
struct SocketAddress {
    /// IP address (e.g. "192.168.1.1").
    address: String,
    /// Port number.
    port: u16,
}

impl FromLua for SocketAddress {
    fn from_lua(value: Value, lua: &Lua) -> mlua::Result<Self> {
        lua.from_value(value)
    }
}

impl IntoLua for SocketAddress {
    fn into_lua(self, lua: &Lua) -> mlua::Result<Value> {
        lua.to_value(&self)
    }
}

impl From<SocketAddr> for SocketAddress {
    fn from(addr: SocketAddr) -> Self {
        Self {
            address: addr.ip().to_string(),
            port: addr.port(),
        }
    }
}

impl SocketAddress {
    fn to_socket_addr(&self) -> mlua::Result<SocketAddr> {
        let ip: std::net::IpAddr = self.address.parse().map_err(|e| {
            mlua::Error::runtime(format!("invalid IP address '{}': {e}", self.address))
        })?;
        Ok(SocketAddr::new(ip, self.port))
    }
}

#[derive(Clone, Debug, Deserialize)]
#[harmony_macros::interface]
struct UdpBindOptions {
    /// Local address to bind (e.g. "0.0.0.0").
    address: String,
    /// Local port to bind.
    port: u16,
    /// Enable SO_BROADCAST on the socket.
    broadcast: Option<bool>,
}

impl FromLua for UdpBindOptions {
    fn from_lua(value: Value, lua: &Lua) -> mlua::Result<Self> {
        lua.from_value(value)
    }
}

#[derive(Clone, Debug, Deserialize)]
#[harmony_macros::interface]
struct TcpConnectOptions {
    /// Host to connect to (IP address or hostname).
    host: String,
    /// Port to connect to.
    port: u16,
    /// Connection timeout in seconds.
    timeout: Option<f64>,
}

impl FromLua for TcpConnectOptions {
    fn from_lua(value: Value, lua: &Lua) -> mlua::Result<Self> {
        lua.from_value(value)
    }
}

#[derive(Clone, Debug, Deserialize)]
#[harmony_macros::interface]
struct TcpBindOptions {
    /// Local address to bind (e.g. "0.0.0.0").
    address: String,
    /// Local port to listen on.
    port: u16,
}

impl FromLua for TcpBindOptions {
    fn from_lua(value: Value, lua: &Lua) -> mlua::Result<Self> {
        lua.from_value(value)
    }
}

const MAX_READ_BYTES: usize = 8 * 1024 * 1024; // 8 MB
const UDP_MAX_DATAGRAM: usize = 65535;

fn validate_timeout(secs: f64) -> mlua::Result<Duration> {
    if secs <= 0.0 || secs.is_nan() || secs.is_infinite() {
        return Err(mlua::Error::runtime(
            "timeout must be a finite number greater than 0",
        ));
    }
    Ok(Duration::from_secs_f64(secs))
}

fn set_timeout(timeout_mutex: &StdMutex<Option<f64>>, timeout: Option<f64>) -> mlua::Result<()> {
    if let Some(secs) = timeout {
        validate_timeout(secs)?;
    }
    let mut guard = timeout_mutex.lock().unwrap_or_else(|e| e.into_inner());
    *guard = timeout;
    Ok(())
}

fn effective_timeout(
    per_op: Option<f64>,
    socket_default: &StdMutex<Option<f64>>,
) -> mlua::Result<Option<Duration>> {
    let secs = per_op.or_else(|| *socket_default.lock().unwrap_or_else(|e| e.into_inner()));
    match secs {
        Some(s) => Ok(Some(validate_timeout(s)?)),
        None => Ok(None),
    }
}

async fn with_optional_timeout<F, T>(timeout: Option<Duration>, fut: F) -> mlua::Result<T>
where
    F: std::future::Future<Output = mlua::Result<T>>,
{
    match timeout {
        Some(duration) => tokio::time::timeout(duration, fut)
            .await
            .map_err(|_| mlua::Error::runtime("operation timed out"))?,
        None => fut.await,
    }
}

#[derive(Clone)]
struct UdpSocket {
    // RwLock allows concurrent I/O (read) while connect/close take exclusive (write) access.
    inner: Arc<TokioRwLock<Option<Arc<TokioUdpSocket>>>>,
    timeout: Arc<StdMutex<Option<f64>>>,
    local_addr: Arc<StdMutex<SocketAddress>>,
}

#[harmony_macros::implementation]
impl UdpSocket {
    /// Sets the default timeout in seconds for all subsequent operations. Pass nil to clear.
    pub fn set_timeout(&self, seconds: Option<f64>) -> mlua::Result<()> {
        set_timeout(&self.timeout, seconds)
    }

    /// Returns the local address this socket is bound to. After `connect`, reflects the
    /// interface used to reach the peer.
    pub fn address(&self) -> SocketAddress {
        self.local_addr
            .lock()
            .unwrap_or_else(|e| e.into_inner())
            .clone()
    }

    /// Associates the socket with a remote address. After connecting, use `send` and `recv`
    /// instead of `send_to` and `recv_from`. Also updates `address()` to reflect the local
    /// interface used to reach the peer.
    pub async fn connect(&self, address: SocketAddress) -> mlua::Result<()> {
        let guard = self.inner.write().await;
        let socket = guard
            .as_ref()
            .ok_or_else(|| mlua::Error::runtime("socket is closed"))?;
        let addr = address.to_socket_addr()?;
        socket
            .connect(addr)
            .await
            .map_err(|e| mlua::Error::runtime(format!("connect failed: {e}")))?;

        let local = socket
            .local_addr()
            .map(SocketAddress::from)
            .map_err(|e| mlua::Error::runtime(format!("failed to get local address: {e}")))?;
        *self.local_addr.lock().unwrap_or_else(|e| e.into_inner()) = local;
        Ok(())
    }

    /// Sends a datagram on a connected socket. Call `connect` first.
    #[harmony(args(data: String, timeout: Option<f64>))]
    pub async fn send(&self, data: mlua::String, timeout: Option<f64>) -> mlua::Result<()> {
        let guard = self.inner.read().await;
        let socket = guard
            .as_ref()
            .ok_or_else(|| mlua::Error::runtime("socket is closed"))?;
        let timeout = effective_timeout(timeout, &self.timeout)?;
        // Copy bytes out of the mlua::String — it is not Send.
        let bytes = data.as_bytes().to_vec();

        with_optional_timeout(timeout, async {
            socket
                .send(&bytes)
                .await
                .map_err(|e| mlua::Error::runtime(format!("send failed: {e}")))?;
            Ok(())
        })
        .await
    }

    /// Receives a datagram on a connected socket. Call `connect` first.
    pub async fn recv(&self, timeout: Option<f64>) -> mlua::Result<LuaBytes> {
        let guard = self.inner.read().await;
        let socket = guard
            .as_ref()
            .ok_or_else(|| mlua::Error::runtime("socket is closed"))?;
        let timeout = effective_timeout(timeout, &self.timeout)?;

        let mut buf = vec![0u8; UDP_MAX_DATAGRAM];
        let n = with_optional_timeout(timeout, async {
            socket
                .recv(&mut buf)
                .await
                .map_err(|e| mlua::Error::runtime(format!("recv failed: {e}")))
        })
        .await?;

        buf.truncate(n);
        Ok(LuaBytes(buf))
    }

    /// Receives a datagram. Returns the data and the sender address. Yields until data arrives.
    #[harmony(returns(LuaBytes, SocketAddress))]
    pub async fn recv_from(&self, timeout: Option<f64>) -> mlua::Result<(LuaBytes, SocketAddress)> {
        let guard = self.inner.read().await;
        let socket = guard
            .as_ref()
            .ok_or_else(|| mlua::Error::runtime("socket is closed"))?;
        let timeout = effective_timeout(timeout, &self.timeout)?;

        let mut buf = vec![0u8; UDP_MAX_DATAGRAM];
        let (n, addr) = with_optional_timeout(timeout, async {
            socket
                .recv_from(&mut buf)
                .await
                .map_err(|e| mlua::Error::runtime(format!("recv_from failed: {e}")))
        })
        .await?;

        buf.truncate(n);
        Ok((LuaBytes(buf), SocketAddress::from(addr)))
    }

    /// Sends a datagram to the specified address.
    #[harmony(args(data: String, address: SocketAddress, timeout: Option<f64>))]
    pub async fn send_to(
        &self,
        data: mlua::String,
        address: SocketAddress,
        timeout: Option<f64>,
    ) -> mlua::Result<()> {
        let guard = self.inner.read().await;
        let socket = guard
            .as_ref()
            .ok_or_else(|| mlua::Error::runtime("socket is closed"))?;
        let timeout = effective_timeout(timeout, &self.timeout)?;
        let addr = address.to_socket_addr()?;
        // Copy bytes out of the mlua::String — it is not Send.
        let bytes = data.as_bytes().to_vec();

        with_optional_timeout(timeout, async {
            socket
                .send_to(&bytes, addr)
                .await
                .map_err(|e| mlua::Error::runtime(format!("send_to failed: {e}")))?;
            Ok(())
        })
        .await
    }

    /// Closes the socket. Further operations will throw.
    pub async fn close(&self) -> mlua::Result<()> {
        let mut guard = self.inner.write().await;
        *guard = None;
        Ok(())
    }
}

harmony_macros::compile!(type_path = UdpSocket, methods = true);

#[derive(Clone)]
struct TcpStream {
    // No inner Arc — read/write need &mut self, so access is serialized.
    inner: Arc<TokioMutex<Option<TokioTcpStream>>>,
    timeout: Arc<StdMutex<Option<f64>>>,
    local_addr: SocketAddress,
}

#[harmony_macros::implementation]
impl TcpStream {
    /// Sets the default timeout in seconds for all subsequent operations. Pass nil to clear.
    pub fn set_timeout(&self, seconds: Option<f64>) -> mlua::Result<()> {
        set_timeout(&self.timeout, seconds)
    }

    /// Returns the local address this socket is bound to.
    pub fn address(&self) -> SocketAddress {
        self.local_addr.clone()
    }

    /// Reads up to max_bytes (max 8 MB). Yields until at least 1 byte arrives. Returns empty string on EOF.
    pub async fn read(&self, max_bytes: usize, timeout: Option<f64>) -> mlua::Result<LuaBytes> {
        if max_bytes == 0 {
            return Err(mlua::Error::runtime("max_bytes must be greater than 0"));
        }
        if max_bytes > MAX_READ_BYTES {
            return Err(mlua::Error::runtime(format!(
                "max_bytes exceeds limit of {MAX_READ_BYTES} (8 MB)"
            )));
        }

        let timeout = effective_timeout(timeout, &self.timeout)?;
        let mut guard = self.inner.lock().await;
        let stream = guard
            .as_mut()
            .ok_or_else(|| mlua::Error::runtime("stream is closed"))?;

        let mut buf = vec![0u8; max_bytes];
        let n = with_optional_timeout(timeout, async {
            stream
                .read(&mut buf)
                .await
                .map_err(|e| mlua::Error::runtime(format!("read failed: {e}")))
        })
        .await?;

        buf.truncate(n);
        Ok(LuaBytes(buf))
    }

    /// Writes all bytes to the stream. Yields until fully written.
    #[harmony(args(data: String, timeout: Option<f64>))]
    pub async fn write(&self, data: mlua::String, timeout: Option<f64>) -> mlua::Result<()> {
        let timeout = effective_timeout(timeout, &self.timeout)?;
        let mut guard = self.inner.lock().await;
        let stream = guard
            .as_mut()
            .ok_or_else(|| mlua::Error::runtime("stream is closed"))?;

        // Copy bytes out of the mlua::String — it is not Send.
        let bytes = data.as_bytes().to_vec();
        with_optional_timeout(timeout, async {
            stream
                .write_all(&bytes)
                .await
                .map_err(|e| mlua::Error::runtime(format!("write failed: {e}")))
        })
        .await
    }

    /// Closes the stream. Further operations will throw.
    pub async fn close(&self) -> mlua::Result<()> {
        let mut guard = self.inner.lock().await;
        if let Some(mut stream) = guard.take() {
            // Graceful shutdown (FIN). Errors are ignored — the stream
            // is being dropped regardless.
            let _ = stream.shutdown().await;
        }
        Ok(())
    }
}

harmony_macros::compile!(type_path = TcpStream, methods = true);

#[derive(Clone)]
struct TcpListener {
    inner: Arc<TokioMutex<Option<Arc<TokioTcpListener>>>>,
    timeout: Arc<StdMutex<Option<f64>>>,
    local_addr: SocketAddress,
}

#[harmony_macros::implementation]
impl TcpListener {
    /// Sets the default timeout in seconds for all subsequent operations. Pass nil to clear.
    pub fn set_timeout(&self, seconds: Option<f64>) -> mlua::Result<()> {
        set_timeout(&self.timeout, seconds)
    }

    /// Returns the local address this socket is bound to.
    pub fn address(&self) -> SocketAddress {
        self.local_addr.clone()
    }

    /// Accepts a new connection. Yields until a client connects. Returns the stream and the client address.
    #[harmony(returns(TcpStream, SocketAddress))]
    pub async fn accept(&self, timeout: Option<f64>) -> mlua::Result<(TcpStream, SocketAddress)> {
        let listener = {
            let guard = self.inner.lock().await;
            guard
                .as_ref()
                .cloned()
                .ok_or_else(|| mlua::Error::runtime("listener is closed"))?
        };
        let timeout = effective_timeout(timeout, &self.timeout)?;

        let (stream, addr) = with_optional_timeout(timeout, async {
            listener
                .accept()
                .await
                .map_err(|e| mlua::Error::runtime(format!("accept failed: {e}")))
        })
        .await?;

        let local_addr = stream
            .local_addr()
            .map(SocketAddress::from)
            .map_err(|e| mlua::Error::runtime(format!("failed to get local address: {e}")))?;
        let tcp_stream = TcpStream {
            inner: Arc::new(TokioMutex::new(Some(stream))),
            timeout: Arc::new(StdMutex::new(None)),
            local_addr,
        };
        Ok((tcp_stream, SocketAddress::from(addr)))
    }

    /// Closes the listener. Further operations will throw.
    pub async fn close(&self) -> mlua::Result<()> {
        let mut guard = self.inner.lock().await;
        *guard = None;
        Ok(())
    }
}

harmony_macros::compile!(type_path = TcpListener, methods = true);

fn parse_bind_address(address: &str, port: u16) -> mlua::Result<SocketAddr> {
    let ip: std::net::IpAddr = address
        .parse()
        .map_err(|e| mlua::Error::runtime(format!("invalid bind address '{address}': {e}")))?;
    Ok(SocketAddr::new(ip, port))
}

async fn udp_bind(options: UdpBindOptions) -> mlua::Result<UdpSocket> {
    let addr = parse_bind_address(&options.address, options.port)?;

    let socket = TokioUdpSocket::bind(addr)
        .await
        .map_err(|e| mlua::Error::runtime(format!("failed to bind UDP socket: {e}")))?;

    if options.broadcast.unwrap_or(false) {
        socket
            .set_broadcast(true)
            .map_err(|e| mlua::Error::runtime(format!("failed to enable broadcast: {e}")))?;
    }

    let local_addr = socket
        .local_addr()
        .map(SocketAddress::from)
        .map_err(|e| mlua::Error::runtime(format!("failed to get local address: {e}")))?;

    Ok(UdpSocket {
        inner: Arc::new(TokioRwLock::new(Some(Arc::new(socket)))),
        timeout: Arc::new(StdMutex::new(None)),
        local_addr: Arc::new(StdMutex::new(local_addr)),
    })
}

async fn tcp_connect(options: TcpConnectOptions) -> mlua::Result<TcpStream> {
    let addr = format!("{}:{}", options.host, options.port);

    let timeout = options.timeout.map(validate_timeout).transpose()?;
    let connect_fut = TokioTcpStream::connect(&addr);
    let stream = match timeout {
        Some(duration) => tokio::time::timeout(duration, connect_fut)
            .await
            .map_err(|_| mlua::Error::runtime("connection timed out"))?,
        None => connect_fut.await,
    }
    .map_err(|e| mlua::Error::runtime(format!("failed to connect: {e}")))?;

    let local_addr = stream
        .local_addr()
        .map(SocketAddress::from)
        .map_err(|e| mlua::Error::runtime(format!("failed to get local address: {e}")))?;

    Ok(TcpStream {
        inner: Arc::new(TokioMutex::new(Some(stream))),
        timeout: Arc::new(StdMutex::new(None)),
        local_addr,
    })
}

async fn tcp_bind(options: TcpBindOptions) -> mlua::Result<TcpListener> {
    let addr = parse_bind_address(&options.address, options.port)?;

    let listener = TokioTcpListener::bind(addr)
        .await
        .map_err(|e| mlua::Error::runtime(format!("failed to bind TCP listener: {e}")))?;

    let local_addr = listener
        .local_addr()
        .map(SocketAddress::from)
        .map_err(|e| mlua::Error::runtime(format!("failed to get local address: {e}")))?;

    Ok(TcpListener {
        inner: Arc::new(TokioMutex::new(Some(Arc::new(listener)))),
        timeout: Arc::new(StdMutex::new(None)),
        local_addr,
    })
}

pub fn get_module() -> Module {
    Module {
        path: "harmony/net".into(),
        setup: Arc::new(|lua: &Lua| -> anyhow::Result<mlua::Table> {
            let table = lua.create_table()?;
            table.set(
                "udp_bind",
                lua.create_async_function(|_, options: UdpBindOptions| async move {
                    udp_bind(options).await
                })?,
            )?;
            table.set(
                "tcp_connect",
                lua.create_async_function(|_, options: TcpConnectOptions| async move {
                    tcp_connect(options).await
                })?,
            )?;
            table.set(
                "tcp_bind",
                lua.create_async_function(|_, options: TcpBindOptions| async move {
                    tcp_bind(options).await
                })?,
            )?;
            Ok(table)
        }),
        scope: harmony_core::Scope {
            id: "harmony.net".into(),
            description: "Open raw TCP and UDP sockets.",
            danger: harmony_core::Danger::High,
        },
    }
}

struct NetModuleDocs;

impl NetModuleDocs {
    fn module_descriptor() -> harmony_luau::ModuleDescriptor {
        harmony_luau::ModuleDescriptor {
            name: "Net",
            local_name: "net",
            description: Some("UDP and TCP socket networking."),
            functions: vec![
                harmony_luau::ModuleFunctionDescriptor {
                    path: vec!["udp_bind"],
                    description: Some("Binds a UDP socket to a local address and port."),
                    params: vec![harmony_luau::ParameterDescriptor {
                        name: "options",
                        ty: UdpBindOptions::luau_type(),
                        description: None,
                        variadic: false,
                    }],
                    returns: vec![LuauType::literal("UdpSocket")],
                    yields: true,
                },
                harmony_luau::ModuleFunctionDescriptor {
                    path: vec!["tcp_connect"],
                    description: Some(
                        "Connects to a remote TCP host. Hostnames are resolved automatically.",
                    ),
                    params: vec![harmony_luau::ParameterDescriptor {
                        name: "options",
                        ty: TcpConnectOptions::luau_type(),
                        description: None,
                        variadic: false,
                    }],
                    returns: vec![LuauType::literal("TcpStream")],
                    yields: true,
                },
                harmony_luau::ModuleFunctionDescriptor {
                    path: vec!["tcp_bind"],
                    description: Some("Binds a TCP listener to a local address and port."),
                    params: vec![harmony_luau::ParameterDescriptor {
                        name: "options",
                        ty: TcpBindOptions::luau_type(),
                        description: None,
                        variadic: false,
                    }],
                    returns: vec![LuauType::literal("TcpListener")],
                    yields: true,
                },
            ],
        }
    }
}

pub fn render_luau_definition() -> Result<String, std::fmt::Error> {
    render_definition_file_with_support(
        &NetModuleDocs::module_descriptor(),
        &[],
        &[
            SocketAddress::interface_descriptor(),
            UdpBindOptions::interface_descriptor(),
            TcpConnectOptions::interface_descriptor(),
            TcpBindOptions::interface_descriptor(),
        ],
        &[
            UdpSocket::class_descriptor(),
            TcpStream::class_descriptor(),
            TcpListener::class_descriptor(),
        ],
    )
}

#[cfg(test)]
mod tests {
    use super::{
        get_module,
        render_luau_definition,
        validate_timeout,
    };
    use mlua::{
        Function,
        Lua,
    };

    #[test]
    fn module_registers_net_exports() {
        let module = get_module();
        assert_eq!(&*module.path, "harmony/net");

        let lua = Lua::new();
        let table = (module.setup)(&lua).expect("create harmony/net module table");

        let _: Function = table.get("udp_bind").expect("register udp_bind");
        let _: Function = table.get("tcp_connect").expect("register tcp_connect");
        let _: Function = table.get("tcp_bind").expect("register tcp_bind");
    }

    #[test]
    fn renders_net_module_definition() {
        let rendered = render_luau_definition().expect("render harmony/net docs");

        assert!(rendered.contains("@class Net"));
        assert!(rendered.contains("@interface SocketAddress"));
        assert!(rendered.contains("@interface UdpBindOptions"));
        assert!(rendered.contains("@interface TcpConnectOptions"));
        assert!(rendered.contains("@interface TcpBindOptions"));
        assert!(rendered.contains("function net.udp_bind(options: UdpBindOptions): UdpSocket"));
    }

    #[test]
    fn validate_timeout_rejects_invalid_values() {
        assert!(validate_timeout(-1.0).is_err());
        assert!(validate_timeout(0.0).is_err());
        assert!(validate_timeout(f64::NAN).is_err());
        assert!(validate_timeout(f64::INFINITY).is_err());
        assert!(validate_timeout(f64::NEG_INFINITY).is_err());
        assert!(validate_timeout(5.0).is_ok());
        assert!(validate_timeout(0.001).is_ok());
    }
}
